Name Fahmida Akhter

Labpartner(s)

In [1]:
#import statements go here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lab 4.1

## Instructions

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. Put the name of your lab partner above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your **completed score** for the chapter assigned in datacamp to the assignment tab in Moodle.

# Warmups 4.1

W.1-3 Do exercises 1-3 in the Data Statisics problem: http://scipy-lectures.org/intro/numpy/exercises.html#data-statistics. See lab 3.2  on how to load in the data file

In [2]:
data_pd = pd.read_csv('http://scipy-lectures.org/_downloads/populations.txt', sep = '\t', index_col = '# year')
data_pd

hare     lynx  carrot
# year                          
1900    30000.0   4000.0   48300
1901    47200.0   6100.0   48200
1902    70200.0   9800.0   41500
1903    77400.0  35200.0   38200
1904    36300.0  59400.0   40600
1905    20600.0  41700.0   39800
1906    18100.0  19000.0   38600
1907    21400.0  13000.0   42300
1908    22000.0   8300.0   44500
1909    25400.0   9100.0   42100
1910    27100.0   7400.0   46000
1911    40300.0   8000.0   46800
1912    57000.0  12300.0   43800
1913    76600.0  19500.0   40900
1914    52300.0  45700.0   39400
1915    19500.0  51100.0   39000
1916    11200.0  29700.0   36700
1917     7600.0  15800.0   41800
1918    14600.0   9700.0   43300
1919    16200.0  10100.0   41300
1920    24700.0   8600.0   47300

W.1 The mean and std of the populations of each species for the years in the period.

In [3]:
mean_values = data_pd[['hare', 'lynx', 'carrot']].mean()
print(mean_values)

hare      34080.952381
lynx      20166.666667
carrot    42400.000000
dtype: float64


In [4]:
std_values = data_pd[['hare', 'lynx', 'carrot']].std()
print(std_values)

hare      21413.981859
lynx      16655.999920
carrot     3404.555771
dtype: float64


W.2 Which year each species had the largest population.

In [8]:
#importing the data file 
data_nt = np.loadtxt('http://scipy-lectures.org/_downloads/populations.txt')

In [10]:
data_nt

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [12]:
#subset an array for each of the columns
hare = data_nt[:,1]
lynx = data_nt[:,2]
carrots = data_nt[:,3]
years = data_nt[:,0]

In [22]:
#where is the max
np.max(hare)

77400.0

In [23]:
np.max(carrots)

48300.0

In [24]:
np.max(lynx)

59400.0

In [25]:
#determine the index value for where max hare population is 
np.where(hare == 77400)

(array([3], dtype=int64),)

In [32]:
#Year of max HARE 
years[3]

1903.0

In [33]:
#determine the index value for where max carrots population is 
np.where(carrots == 48300)

(array([0], dtype=int64),)

In [34]:
#Year of max Carrots 
years[0]

1900.0

In [35]:
#determine the index value for where max lynx population is 
np.where(lynx == 59400)

(array([4], dtype=int64),)

In [36]:
#Year of max lynx 
years[4]

1904.0

In [38]:
#create pop_array which excludes years data 
Pop_array = data_nt[:,1:4]
Pop_array

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [40]:
np.argsort(Pop_array)

array([[1, 0, 2],
       [1, 0, 2],
       [1, 2, 0],
       [1, 2, 0],
       [0, 2, 1],
       [0, 2, 1],
       [0, 1, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 2, 0],
       [1, 2, 0],
       [2, 1, 0],
       [0, 2, 1],
       [0, 1, 2],
       [0, 1, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2]], dtype=int64)

In [41]:
max_species = np.argmax(Pop_array, axis = 1)

In [42]:
species = np.array(['Hare', 'Lynx', 'Carrot'])
max_species1= species[max_species]

In [43]:
maxpop_years= np.column_stack((years,max_species1))

In [44]:
maxpop_years

array([['1900.0', 'Carrot'],
       ['1901.0', 'Carrot'],
       ['1902.0', 'Hare'],
       ['1903.0', 'Hare'],
       ['1904.0', 'Lynx'],
       ['1905.0', 'Lynx'],
       ['1906.0', 'Carrot'],
       ['1907.0', 'Carrot'],
       ['1908.0', 'Carrot'],
       ['1909.0', 'Carrot'],
       ['1910.0', 'Carrot'],
       ['1911.0', 'Carrot'],
       ['1912.0', 'Hare'],
       ['1913.0', 'Hare'],
       ['1914.0', 'Hare'],
       ['1915.0', 'Lynx'],
       ['1916.0', 'Carrot'],
       ['1917.0', 'Carrot'],
       ['1918.0', 'Carrot'],
       ['1919.0', 'Carrot'],
       ['1920.0', 'Carrot']], dtype='<U32')

# Lecture 4.1

Agenda:

- Checking in after the hurricane, how is everyone doing?
- Coding questions
- Tabs in python

Some relevant coding humor: https://www.youtube.com/watch?v=JfEIkkDkrmE

Let's go over some of the examples here: https://scipy-lectures.org/intro/language/control_flow.html

In [13]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [15]:
# if statement

if (x[1] == 3):
    print('yes') # there is a tab before the print statement
    
print('Hello')    # this is not part of the if statement


Hello


In [16]:
if x[0] ==5:
    print('yes')
elif x[0] ==1:
    print('yes')
else:
    print('end of the program')

yes


In [17]:
if x[0] ==5:
    print('yes')
elif x[0] ==10:
    print('yes')
else:
    print('end of the program')

end of the program


In [ ]:
y = np.array([4,7,6])
y

In [ ]:
if (y[-1] > 7):
    print("Excellent")

print('Bogus')

# Lab 4.1

**E.1** Complete intermediate python chapter 3: Logic, Control Flow and Filtering

Note that the tutorials here have similar material for your needs:
https://github.com/chsharrison/Sci_comp_F24/blob/main/Course_materials/resources.md

**E.2** Make notes for yourself on all of the progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [46]:
#Comparing arrays 
array_1 = np.array([18,15,25])

array_1>16 #this returns True for the numbers that ARE greater than 13

array([ True, False,  True])

In [47]:
#comparing two arrays 
array_2 = np.array([20,13,30])

array_2>array_1 #returns True for where array 2 is greater than array 1

array([ True, False,  True])

In [49]:
np.logical_and(array_1>1, array_1>array_2)

array([False,  True, False])

In [50]:
array_1[1]>12 and array_1[1]>array_2[1]

True

**E.3** Exercise 1 on https://www.practicepython.org

In [52]:
name = input("Give me your name:  ")
print("Your name is " + name)

Give me your name:   Fahmida


Your name is Fahmida


In [53]:
age = input(name + (", what is your age?"))

Fahmida, what is your age? 32


**E.4** Exercise 2 on https://www.practicepython.org

In [54]:
#input a number 
num = input("Hi! Input a number:")

Hi! Input a number: 14


In [56]:
#even or odd
if int(num)%2 == 0:
    print("Your number is even")
else:
    print("Your number is odd")

Your number is even


In [58]:
#If the number is a multiple of 4, print out a different message.
if int(num)%4 == 0:
    print("your number is multiple of 4 and it is even")
elif int(num)%2 == 0:
        print("Your number is even")
else: 
    print("Your number is odd")

Your number is even


Don't forget to do some practicing of what you have been learning, including material from previous labs

**You did it!**