Name: Mariam Valladares

Labpartner(s): Sarah Brannum

In [1]:
#import statements go here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lab 4.1

## Instructions

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. Put the name of your lab partner above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your **completed score** for the chapter assigned in datacamp to the assignment tab in Moodle.

# Warmups 4.1

W.1-3 Do exercises 1-3 in the Data Statisics problem: http://scipy-lectures.org/intro/numpy/exercises.html#data-statistics. See lab 4.1  on how to load in the data file

**Data Statistics Questions**
1. The mean and std of the populations of each species for the years in the period.
2. Which year each species had the largest population.
3. Which species has the largest population for each year. (Hint: argsort & fancy indexing of np.array(['H', 'L', 'C']))

In [13]:
# read the data
data = np.loadtxt('populations.txt')

0        1        2        3
0  1900.0  30000.0   4000.0  48300.0
1  1901.0  47200.0   6100.0  48200.0
2  1902.0  70200.0   9800.0  41500.0
3  1903.0  77400.0  35200.0  38200.0
4  1904.0  36300.0  59400.0  40600.0

In [17]:
# 1. mean by species
species = {'Mean':{'hares': np.mean(data[:,1]), 'lynx':np.mean(data[:,2]), 'carrot': np.mean(data[:,3])},
           'Std':{'hares': np.std(data[:,1]), 'lynx':np.std(data[:,2]), 'carrot': np.std(data[:,3])}
          }
species
# Make it a table to visualize
species_df = pd.DataFrame(species)

species_df

Mean           Std
hares   34080.952381  20897.906458
lynx    20166.666667  16254.591537
carrot  42400.000000   3322.506226

In [24]:
# 2. year in which species had the largest population
data_df = pd.read_csv('populations.txt', sep= '\t', index_col = 0 )

data_df

hare     lynx  carrot
# year                          
1900    30000.0   4000.0   48300
1901    47200.0   6100.0   48200
1902    70200.0   9800.0   41500
1903    77400.0  35200.0   38200
1904    36300.0  59400.0   40600
1905    20600.0  41700.0   39800
1906    18100.0  19000.0   38600
1907    21400.0  13000.0   42300
1908    22000.0   8300.0   44500
1909    25400.0   9100.0   42100
1910    27100.0   7400.0   46000
1911    40300.0   8000.0   46800
1912    57000.0  12300.0   43800
1913    76600.0  19500.0   40900
1914    52300.0  45700.0   39400
1915    19500.0  51100.0   39000
1916    11200.0  29700.0   36700
1917     7600.0  15800.0   41800
1918    14600.0   9700.0   43300
1919    16200.0  10100.0   41300
1920    24700.0   8600.0   47300

In [26]:
#hares
np.argmax(data_df.iloc[:,[0]])

3

In [27]:
#lynx
np.argmax(data_df.iloc[:,[1]])

4

In [28]:
#Carrot
np.argmax(data_df.iloc[:,[2]])

0

**Answer** For hares the year was 1903, for Lynx was 1904, and for carrot 1900

In [36]:
# 3 Which species has the largest population for each year
maxValues = data_df.idxmax(axis=1)

maxValues

# year
1900    carrot
1901    carrot
1902      hare
1903      hare
1904      lynx
1905      lynx
1906    carrot
1907    carrot
1908    carrot
1909    carrot
1910    carrot
1911    carrot
1912      hare
1913      hare
1914      hare
1915      lynx
1916    carrot
1917    carrot
1918    carrot
1919    carrot
1920    carrot
dtype: object

# Lecture 4.1

Agenda:

- Checking in after the hurricane, how is everyone doing?
- Coding questions
- Tabs in python

Some relevant coding humor: https://www.youtube.com/watch?v=JfEIkkDkrmE

Let's go over some of the examples here: https://scipy-lectures.org/intro/language/control_flow.html

In [33]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [34]:
if x[0] == 1:
    print('yes')

yes


In [35]:
# if statement

if (x[1] == 3):
    print('yes') # there is a tab before the print statement
    
print('Hello')    # this is not part of the if statement


Hello


In [37]:
x[1] == 2

True

In [38]:
y = np.array([4,7,6])
y

array([4, 7, 6])

In [39]:
if (y[-1] > 7):
    print("Excellent")

print('Bogus')

Bogus


# Lab 4.1

**E.1** Complete intermediate python chapter 3: Logic, Control Flow and Filtering

Note that the tutorials here have similar material for your needs:
https://github.com/chsharrison/Sci_comp_F24/blob/main/Course_materials/resources.md

**E.2** Make notes for yourself on all of the progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [86]:
## Comparison Operators applicable to strings, boolean and numbers (integers or floats) as well as arrays
# Comparison of booleans
"True" == "False"

# Comparison of integers
-5 * 15 != 75

# Comparison of strings
"pyscript" == "PyScript"

# Compare a boolean with an integer
True == 1

#greater than
x = -3 * 6
print(x >= -10)

#less than
y = "test"
print("test" <= y) 

True

In [87]:
## Boolean operators "and", "or", "not"
my_kitchen = 18.0
your_kitchen = 14.0

#AND
my_kitchen > 10 and my_kitchen < 18

#OR
my_kitchen < 14 or my_kitchen > 17

#NOT
x = 8
y = 9
not(not(x < 3) and not(y > 14 or y > 10))

False

In [89]:
# Boolean operators with Numpy arrays: Previous booleans operators cannot be used for numpy arrays therefore requires the 
#use of specific functions within the numpy package.
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

#AND
np.logical_and(my_house<11, your_house<11)

#OR
np.logical_or(my_house > 18.5, my_house < 10)

array([False,  True, False,  True])

In [90]:
# Conditional if, elif, else
# Define variables
room = "kit"
area = 14.0

# if statement for room
if room == "kit" :  #here defines the condition
    print("looking around in the kitchen.")  ## what to print if the condition is True
    
# adding the else 
if room == "kit" :
    print("looking around in the kitchen.")
else :
    print("looking around elsewhere.") ## what to print if the condition is False
    
# setting two conditions, if meets one of them will print the define statement

if room == "kit" :
    print("looking around in the kitchen.")
elif room == "bed":
    print("looking around in the bedroom.")  # if first condition is not met, will evaluate the second condition and print if True.
else :
    print("looking around elsewhere.")


looking around in the kitchen.
looking around in the kitchen.
looking around in the kitchen.


In [103]:
## Filtering pandas dataframes
# Import cars data
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)
cars

# Extract drives_right column as Series: dr
dr = cars['cars_per_cap']

# Use dr to subset cars: sel
sel = cars[dr]

# can also use the booleans to subset
# Create car_maniac: observations that have a cars_per_cap over 500
cpc = cars['cars_per_cap']
many_cars =  cpc > 500

## use it to subset the original data
car_maniac = cars[many_cars]


# Can also use np.boolean operators
# Create medium: observations with cars_per_cap between 100 and 500
cpc = cars['cars_per_cap']
between = np.logical_and(cpc >100, cpc < 500)  # such as this one to subset
medium = cars[between]

cars_per_cap    drives_right 
country                               
MOR                500            True
UK                1000            True
AUS                800            True
USA               2000           False
EG                 100           False
IN                 450            True
SD                 250           False

**E.3** Exercise 1 on https://www.practicepython.org

In [41]:
# Ask user to enter their name
name = input("What is your name: ")

What is your name:  Mariam


In [42]:
# Ask user their age
age = int(input("How old are you: "))

How old are you:  32


In [43]:
# Calculate in what year they will turn 100
year = 2024 - age + 100

## the year 
print(name + ", you will be 100 years old in the year " + str(year))

Mariam, you will be 100 years old in the year 2092


In [64]:
#Add on to the previous program by asking the user for another number 
number = input("Insert a number here: ")

Insert a number here:  4


In [65]:
#printing out that many copies of the previous message.
message = name + ", you will be 100 years old in the year " + str(year)
print(message * int(number))

Mariam, you will be 100 years old in the year 2092Mariam, you will be 100 years old in the year 2092Mariam, you will be 100 years old in the year 2092Mariam, you will be 100 years old in the year 2092


In [66]:
#Print out that many copies of the previous message on separate lines. (Hint: the string "\n is the same as pressing the ENTER button)
message2 = message + "\n"
print(message2 * int(number))


Mariam, you will be 100 years old in the year 2092
Mariam, you will be 100 years old in the year 2092
Mariam, you will be 100 years old in the year 2092
Mariam, you will be 100 years old in the year 2092



**E.4** Exercise 2 on https://www.practicepython.org

In [67]:
#Ask the user for a number. 
number2 = input("Insert a number here: ")

Insert a number here:  2


In [70]:
#Depending on whether the number is even or odd, print out an appropriate message to the user.
if int(number2) % 2 == 0: 
    print("Even Number")
else:
    print("Odd Number")


Even Number


In [73]:
#if the number is a multiple of 4, print out a different message.
if int(number2) % 4 == 0:
    print("Number multiple of 4")
else:
    print("Not multiple of 4")

Not multiple of 4


In [74]:
#Ask the user for two numbers: one number to check (call it num) and one number to divide by (check). 
num = input("Define the first number here: ")
check = input("Define the second number here: ")

Define the first number here:  5
Define the second number here:  10


In [85]:
#If check divides evenly into num, tell that to the user. If not, print a different appropriate message.
if int(check) % int(num) == 0:
    print("Your " + check +" is divisible by " + num)
else:
    print("Your " +check +" is not divisible by " + num)

Your 10 is divisible by 5


Don't forget to do some practicing of what you have been learning, including material from previous labs

**You did it!**