Name Zhenwei Wu

Labpartner(s)

In [2]:
# import statements go here
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Class 5.1

# Warmups 5.1

**W.1** Go through 1.4.1.2 Creating Arrays in the scipy lecture notes, including the exercises. http://scipy-lectures.org/intro/numpy/array_object.html#id2

In [18]:
# for a 1D array
a = np.array([0,1,4,5,6])
print(a)

# this 1D array has 5 rows
print(a.shape)

# this 1D array has 1 dimension
print(a.ndim)

# having 5 elements
print(len(a))

[0 1 4 5 6]
(5,)
1
5


In [22]:
# for a 2D array
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b)

# this 2D array has 2 rows and 3 columns
print(b.shape)

# this 2D array has 2 dimensions
print(b.ndim)

# returns the size of the first dimension
print(len(b))

[[0 1 2]
 [3 4 5]]
(2, 3)
2
2


In [26]:
c = np.array([[[1], [2]], [[3], [4]]])

print(c.shape)

# this 3D array has 2 depth, each block has 2 rows and each row has 1 element

(2, 2, 1)


In [ ]:
# function for creating array

In [33]:
# evenly spaced:
# start from 0 to 10, 10 is not included
a = np.arange(0,10)
print (a)

# start from 0 to 10, 10 is not included, step is 2
b = np.arange(0,10,2)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [43]:
# by number of points:
# start:0, end: 4
c = np.linspace(0, 6, 6)
print(c)

# start: 0, end: 1, not included the endpoint
d = np.linspace(0, 1, 5, endpoint=False)
print(d)

[0.  1.2 2.4 3.6 4.8 6. ]
[0.  0.2 0.4 0.6 0.8]


In [49]:
# common arrays
# .ones() means all one
a = np.ones((3, 3))
print(a)

# .zeros() means all zero
b = np.zeros((2, 2))
print(b)

# .eye function is fun
c = np.eye(3)
print(c)

# .diag() is fun
d = np.diag(np.array([1, 2, 3, 4]))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [52]:
# random numbers
# uniform in [0, 1]
a = np.random.rand(4) 
print(a)

# Gaussian
b = np.random.randn(4)
print(b)

[0.05215405 0.30913941 0.65243997 0.31747387]
[-0.2742806   1.3082651  -1.31535658  0.39279676]


# Lecture 5.1

### Agenda:

- Programming questions
- Examples of for loops

# Lab 5.1

**E.1** Complete Lab 4.2 if you haven't allready


**E.2** Complete intermediate python chapter 5: Case study on hacker statistics


**E.3** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [53]:
# put another pdf on moodle

### Congratulations! অভিনন্দন 恭喜 ¡Felicidades! You finished Intermediate Python!