Name Zhenwei Wu

Labpartner(s)

In [1]:
#import statements go here


# Class 9.2

You all will finish presenting your movies from Lab 7.2. 

Today Victoria Garza will give an overview and demo of the LSU HPC system

Reminder your final project proposal is due Monday by 5 PM (note new due date). On Tuesday you will pitch your final project proposal to the class in a short (5 min talk).


# Warmup 9.2

**W.1** Create the following numpy array. Print out the values to check!

[[0. 0. 0. 0. 0. 0. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 5. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 0. 0. 0. 0. 0. 0.]]

In [6]:
import numpy as np

array = np.zeros((7,7))

array[1:6, 1:6] = 1

array[3,3] = 5

print(array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**W.2** Pandas filtering and sorting practice with Chipotle data

Import the dataset from this address https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv
Assign it to a variable called chipo.
1. How many products cost more than $10.00?
2. What is the price of each item?
    1. Print a data frame with only two columns item_name and item_price
    2. Sort by the name of the item
1. What was the quantity of the most expensive item ordered?
1. How many times did someone order more than one Canned Soda?


In [9]:
import pandas as pd

url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

chipo = pd.read_csv(url, sep = '\t')

print(chipo.head())

   order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   


In [18]:
# Convert item_price to a numeric type by removing the dollar sign
chipo['item_price'] = chipo['item_price'].replace('[\$,]', '', regex=True).astype(float)

# Get the number of unique products that cost more than $10.00
expensive_product_types_count = chipo[chipo['item_price']/chipo['quantity'] > 10]['item_name'].nunique()
expensive_product_types_count

<>:2: SyntaxWarning: invalid escape sequence '\$'
<>:2: SyntaxWarning: invalid escape sequence '\$'
C:\Users\punch\AppData\Local\Temp\ipykernel_2088\722120438.py:2: SyntaxWarning: invalid escape sequence '\$'
  chipo['item_price'] = chipo['item_price'].replace('[\$,]', '', regex=True).astype(float)


25

In [19]:
# Filter items that cost more than $10 and drop duplicates to get unique items
expensive_items = chipo[chipo['item_price']/chipo['quantity'] > 10][['item_name', 'item_price']].drop_duplicates()

# Sort the resulting DataFrame by item name
expensive_items_sorted = expensive_items.sort_values(by='item_name')

# Display the sorted DataFrame
print("Items Priced Over $10, Sorted by Name:")
print(expensive_items_sorted)

Items Priced Over $10, Sorted by Name:
              item_name  item_price
4510      Barbacoa Bowl       11.49
39        Barbacoa Bowl       11.75
471       Barbacoa Bowl       11.48
3276   Barbacoa Burrito       11.48
1648   Barbacoa Burrito       11.08
...                 ...         ...
57       Veggie Burrito       11.25
3601     Veggie Burrito       33.75
435      Veggie Burrito       10.98
186   Veggie Salad Bowl       11.25
738   Veggie Soft Tacos       11.25

[62 rows x 2 columns]


In [17]:
# Identify the most expensive item by finding the maximum item price
most_expensive_item = chipo.loc[chipo['item_price'].idxmax()]

# Retrieve the quantity of this most expensive item ordered
most_expensive_item_quantity = most_expensive_item['quantity']

print("Quantity of the most expensive item ordered:", most_expensive_item_quantity)

Quantity of the most expensive item ordered: 15


In [20]:
# Filter for orders of "Canned Soda" where quantity is more than 1
canned_soda_orders = chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)]

# Count the number of such orders
canned_soda_multiple_orders_count = canned_soda_orders.shape[0]

print("Number of times more than one Canned Soda was ordered:", canned_soda_multiple_orders_count)

Number of times more than one Canned Soda was ordered: 20


# Lecture 9.2

### Agenda:

- Questions
- Show us your movies
- Intro to LSU HPC

### Questions

# Lab 9.2

**E.0** Complete the previous labs if you are behind.

**E.1** Submit a screenshot of you using a jupyter notebook on the LSU HPC

**E.2** Complete your final project proposal and submit it in Moodle

**E.3** Prepare a 5 min presentation of your project proposal, including a brief introduction, your research plan, the programming methods you are planning to use, your preliminary results/plots, and your timeline for completion. ​You will present this in class next Tuesday. No late talks this time.

A good target length is 1 slide per minute.

Upload your talk here:
https://lsu.box.com/s/5c95w1s2rrwqy839o3ul3oouzi43s4y1


**Notes** Make notes for yourself on progamming tecniques and commands you learned in the this week, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.