Name: Sharmin Siddika

Labpartner(s): Mariam Valladares

In [1]:
#import statements go here
#import statements go here
#import statements go here
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr

In [2]:
import cartopy.crs as ccrs   #import map styles/types
import cartopy.feature as cfeature  # features such as the ocean, coastlines rivers, etc
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER

# Class 9.2

You all will finish presenting your movies from Lab 7.2. 

Today Victoria Garza will give an overview and demo of the LSU HPC system

Reminder your final project proposal is due Monday by 5 PM (note new due date). On Tuesday you will pitch your final project proposal to the class in a short (5 min talk).


# Warmup 9.2

**W.1** Create the following numpy array. Print out the values to check!

[[0. 0. 0. 0. 0. 0. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 5. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 0. 0. 0. 0. 0. 0.]]

In [3]:
import numpy as np

# Creating the desired numpy array
array = np.array([
    [0., 0., 0., 0., 0., 0., 0.],
    [0., 1., 1., 1., 1., 1., 0.],
    [0., 1., 1., 1., 1., 1., 0.],
    [0., 1., 1., 5., 1., 1., 0.],
    [0., 1., 1., 1., 1., 1., 0.],
    [0., 1., 1., 1., 1., 1., 0.],
    [0., 0., 0., 0., 0., 0., 0.]
])

# Print the array to check
array

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 5., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

**W.2** Pandas filtering and sorting practice with Chipotle data

Import the dataset from this address https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv
Assign it to a variable called chipo.
1. How many products cost more than $10.00?
2. What is the price of each item?
    1. Print a data frame with only two columns item_name and item_price
    2. Sort by the name of the item
1. What was the quantity of the most expensive item ordered?
1. How many times did someone order more than one Canned Soda?


In [4]:
import numpy as np
import pandas as pd
# Load the dataset
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep='\t')
chipo['item_price'] = chipo['item_price'].replace('[\$,]', '', regex=True).astype(float)

# Filter for products that cost more than $10.00 and count unique items
products_over_10 = chipo[chipo['item_price'] > 10.00]
num_products_over_10 = products_over_10['item_name'].nunique()
num_products_over_10

31

In [5]:
import pandas as pd

# Convert item_price to numeric after removing the dollar sign
chipo['item_price'] = chipo['item_price'].replace('[\$,]', '', regex=True).astype(float)

# Group by item_name
item_prices = chipo.groupby('item_name').agg({'item_price': 'mean'}).reset_index()

# Sort by item_name
item_prices_sorted = item_prices.sort_values('item_name')

# Print the result
print(item_prices_sorted[['item_name', 'item_price']])

                                item_name  item_price
0                       6 Pack Soft Drink    6.610185
1                           Barbacoa Bowl   10.187273
2                        Barbacoa Burrito    9.832418
3                   Barbacoa Crispy Tacos   10.928182
4                     Barbacoa Salad Bowl   10.640000
5                     Barbacoa Soft Tacos   10.018400
6                           Bottled Water    1.867654
7                                    Bowl   14.800000
8                                 Burrito    7.400000
9                             Canned Soda    1.320577
10                      Canned Soft Drink    1.457641
11                          Carnitas Bowl   10.833971
12                       Carnitas Burrito   10.132712
13                  Carnitas Crispy Tacos   11.137143
14                         Carnitas Salad    8.990000
15                    Carnitas Salad Bowl   11.056667
16                    Carnitas Soft Tacos    9.398500
17                          

In [6]:
import pandas as pd
chipo['item_price'] = chipo['item_price'].replace('[\$,]', '', regex=True).astype(float)

# Find the row with the most expensive item
most_expensive_order = chipo.loc[chipo['item_price'].idxmax()]

# Extract the quantity of the most expensive item
quantity_most_expensive = most_expensive_order['quantity']

print(quantity_most_expensive)

15


In [7]:
import pandas as pd

# Filter for rows where item_name is "Canned Soda" and quantity is greater than one
canned_soda_orders = chipo[(chipo['item_name'] == "Canned Soda") & (chipo['quantity'] > 1)]

# Count the number of such orders
num_canned_soda_orders = canned_soda_orders.shape[0]

print(num_canned_soda_orders)

20


# Lecture 9.2

### Agenda:

- Questions
- Show us your movies
- Intro to LSU HPC

### Questions

# Lab 9.2

**E.0** Complete the previous labs if you are behind.

**Completed**

**E.1** Submit a screenshot of you using a jupyter notebook on the LSU HPC

**E.2** Complete your final project proposal and submit it in Moodle

**Completed**

**E.3** Prepare a 5 min presentation of your project proposal, including a brief introduction, your research plan, the programming methods you are planning to use, your preliminary results/plots, and your timeline for completion. ​You will present this in class next Tuesday. No late talks this time.

A good target length is 1 slide per minute.

Upload your talk here:
https://lsu.box.com/s/5c95w1s2rrwqy839o3ul3oouzi43s4y1


**Notes** Make notes for yourself on progamming tecniques and commands you learned in the this week, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [ ]:
# Create bar plot of average final grade in each study category
sns.catplot(x="study_time", y="G3",
            data=student_data,
            kind="bar")

# Show plot
plt.show()

In [ ]:
# List of categories from lowest to highest
category_order = ["<2 hours", 
                  "2 to 5 hours", 
                  "5 to 10 hours", 
                  ">10 hours"]

# Use the order parameter to rearrange the categories
sns.catplot(x="study_time", y="G3",
            data=student_data,
            kind="bar",
            order=category_order)

# Show plot
plt.show()

In [ ]:
# Specify the category ordering
study_time_order = ["<2 hours", "2 to 5 hours", 
                    "5 to 10 hours", ">10 hours"]

# Create a box plot and set the order of the categories
sns.catplot(x="study_time", y="G3",
            data=student_data,
            kind="box",  # Make sure to specify the kind as "box"
            order=study_time_order)

# Show plot
plt.show()

In [ ]:
# Create a box plot with subgroups and omit the outliers
sns.catplot(x="internet", y="G3",
            data=student_data,
            kind="box",  # Specify the kind of plot
            hue="location",  # Add subgroups
            sym="")  # Omit the outliers

# Show plot
plt.show()

In [ ]:
# Set the whiskers at the min and max values
sns.catplot(x="romantic", y="G3",
            data=student_data,
            kind="box",
            whis=[0, 100])

# Show plot
plt.show()

In [ ]:
# Create a point plot of family relationship vs. absences
# Check if you have set the x and y parameters correctly
sns.catplot(x="famrel", y="absences", data=student_data, kind="point")
    
# Show plot
plt.show()

In [ ]:
# Remove the lines joining the points
sns.catplot(x="famrel", y="absences",
            data=student_data,
            kind="point",
            capsize=0.2,
            join=False)
# Show plot
plt.show()