Name

Labpartner(s)

In [1]:
#import statements go here


# Class 9.2

You all will finish presenting your movies from Lab 7.2. 

Today Victoria Garza will give an overview and demo of the LSU HPC system

Reminder your final project proposal is due Monday by 5 PM (note new due date). On Tuesday you will pitch your final project proposal to the class in a short (5 min talk).


# Warmup 9.2

**W.1** Create the following numpy array. Print out the values to check!

[[0. 0. 0. 0. 0. 0. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 5. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 0. 0. 0. 0. 0. 0.]]

**W.2** Pandas filtering and sorting practice with Chipotle data

Import the dataset from this address https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv
Assign it to a variable called chipo.
1. How many products cost more than $10.00?
2. What is the price of each item?
    1. Print a data frame with only two columns item_name and item_price
    2. Sort by the name of the item
1. What was the quantity of the most expensive item ordered?
1. How many times did someone order more than one Canned Soda?


# Lecture 9.2

### Agenda:

- Questions
- Show us your movies
- Intro to LSU HPC

### Questions

# Lab 9.2

**E.0** Complete the previous labs if you are behind.

**E.1** Submit a screenshot of you using a jupyter notebook on the LSU HPC

**E.2** Complete your final project proposal and submit it in Moodle

**E.3** Prepare a 5 min presentation of your project proposal, including a brief introduction, your research plan, the programming methods you are planning to use, your preliminary results/plots, and your timeline for completion. ​You will present this in class next Tuesday. No late talks this time.

A good target length is 1 slide per minute.

Upload your talk here:
https://lsu.box.com/s/5c95w1s2rrwqy839o3ul3oouzi43s4y1


**Notes** Make notes for yourself on progamming tecniques and commands you learned in the this week, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.