Name: Israt

Labpartner(s): Fahmida

In [1]:
#import statements go here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lab 4.1

## Instructions

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. Put the name of your lab partner above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your **completed score** for the chapter assigned in datacamp to the assignment tab in Moodle.

# Warmups 4.1

W.1-3 Do exercises 1-3 in the Data Statisics problem: http://scipy-lectures.org/intro/numpy/exercises.html#data-statistics. See lab 4.1  on how to load in the data file

Data loading

In [7]:
data = np.loadtxt('populations.txt')
year, hares, lynxes, carrots = data.T
populations = data[:,1:]

print(populations)

[[30000.  4000. 48300.]
 [47200.  6100. 48200.]
 [70200.  9800. 41500.]
 [77400. 35200. 38200.]
 [36300. 59400. 40600.]
 [20600. 41700. 39800.]
 [18100. 19000. 38600.]
 [21400. 13000. 42300.]
 [22000.  8300. 44500.]
 [25400.  9100. 42100.]
 [27100.  7400. 46000.]
 [40300.  8000. 46800.]
 [57000. 12300. 43800.]
 [76600. 19500. 40900.]
 [52300. 45700. 39400.]
 [19500. 51100. 39000.]
 [11200. 29700. 36700.]
 [ 7600. 15800. 41800.]
 [14600.  9700. 43300.]
 [16200. 10100. 41300.]
 [24700.  8600. 47300.]]


The mean and std of the populations of each species for the years in the period.

In [30]:
print("       Hares, Lynxes, Carrots")
print("Mean:", populations.mean(axis=0))
print("Std:", populations.std(axis=0))


       Hares, Lynxes, Carrots
Mean: [34080.95238095 20166.66666667 42400.        ]
Std: [20897.90645809 16254.59153691  3322.50622558]


Which year each species had the largest population.

In [31]:
j_max_years = np.argmax(populations, axis=0)
print("Max. year:", year[j_max_years])


Max. year: [1903. 1904. 1900.]


Which species has the largest population for each year. (Hint: argsort & fancy indexing of np.array(['H', 'L', 'C']))

In [33]:
max_species = np.argmax(populations, axis=1)
species = np.array(['Hare', 'Lynx', 'Carrot'])
print("Max species:")
print(year)
print(species[max_species])

Max species:
[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]
['Carrot' 'Carrot' 'Hare' 'Hare' 'Lynx' 'Lynx' 'Carrot' 'Carrot' 'Carrot'
 'Carrot' 'Carrot' 'Carrot' 'Hare' 'Hare' 'Hare' 'Lynx' 'Carrot' 'Carrot'
 'Carrot' 'Carrot' 'Carrot']


# Lecture 4.1

Agenda:

- Checking in after the hurricane, how is everyone doing?
- Coding questions
- Tabs in python

Some relevant coding humor: https://www.youtube.com/watch?v=JfEIkkDkrmE

Let's go over some of the examples here: https://scipy-lectures.org/intro/language/control_flow.html

In [11]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [12]:
# if statement

if (x[1] == 3):
    print('yes') # there is a tab before the print statement
    
print('Hello')    # this is not part of the if statement


Hello


In [13]:
x[1] == 2

True

In [14]:
y = np.array([4,7,6])
y

array([4, 7, 6])

In [15]:
if (y[-1] > 7):
    print("Excellent")

print('Bogus')

Bogus


# Lab 4.1

**E.1** Complete intermediate python chapter 3: Logic, Control Flow and Filtering

Note that the tutorials here have similar material for your needs:
https://github.com/chsharrison/Sci_comp_F24/blob/main/Course_materials/resources.md

**E.2** Make notes for yourself on all of the progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

The one thing I have learned so useful is that in Windows, when I copy a path I have to turn each backslash to front manually in R. But in Python we can change it entirely by putting an "r" at the beginning of the pathname

**E.3** Exercise 1 on https://www.practicepython.org

Create a program that asks the user to enter their name and their age. Print out a message addressed to them that tells them the year that they will turn 100 years old.

In [8]:
age = input("Enter your age: ")
age = int(age)
time= 2021+(100-age)
print('You will turn 100 in '+  str(time))

Enter your age:  29


You will turn 100 in 2092


**E.4** Exercise 2 on https://www.practicepython.org

In [10]:
number = input("Enter a number: ")
E4 = int(number) % 2
if E4 == 0:
    print(str(number)+" is an even number")
else:
    print(str(number)+" is an odd number")

Enter a number:  53


53 is an odd number


Don't forget to do some practicing of what you have been learning, including material from previous labs

**You did it!**