Name: Israt

Labpartner(s): Fahmida, Zach

In [1]:
#import statements go here


# Class 9.2

You all will finish presenting your movies from Lab 7.2. 

Today Victoria Garza will give an overview and demo of the LSU HPC system

Reminder your final project proposal is due Monday by 5 PM (note new due date). On Tuesday you will pitch your final project proposal to the class in a short (5 min talk).


# Warmup 9.2

**W.1** Create the following numpy array. Print out the values to check!

[[0. 0. 0. 0. 0. 0. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 5. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 0. 0. 0. 0. 0. 0.]]

**W.2** Pandas filtering and sorting practice with Chipotle data

Import the dataset from this address https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv
Assign it to a variable called chipo.
1. How many products cost more than $10.00?
2. What is the price of each item?
    1. Print a data frame with only two columns item_name and item_price
    2. Sort by the name of the item
1. What was the quantity of the most expensive item ordered?
1. How many times did someone order more than one Canned Soda?


In [1]:
import pandas as pd

# Import the dataset
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep='\t')

# Display the first few rows to understand the data structure
chipo.head()


order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

In [2]:
# Question 01

# Removing the dollar sign from item_price and convert to float
chipo['item_price'] = chipo['item_price'].str.replace('$', '').astype(float)

# Filterin items costing more than $10.00 and count unique items
products_over_10 = chipo[chipo['item_price'] > 10.00]['item_name'].nunique()
print("Number of products costing more than $10.00:", products_over_10)


Number of products costing more than $10.00: 31


In [3]:
# Question 02
# Group by item_name and calculate the mean price
item_prices = chipo.groupby('item_name')['item_price'].mean().reset_index()
print("Price of each item:")
print(item_prices)


Price of each item:
                                item_name  item_price
0                       6 Pack Soft Drink    6.610185
1                           Barbacoa Bowl   10.187273
2                        Barbacoa Burrito    9.832418
3                   Barbacoa Crispy Tacos   10.928182
4                     Barbacoa Salad Bowl   10.640000
5                     Barbacoa Soft Tacos   10.018400
6                           Bottled Water    1.867654
7                                    Bowl   14.800000
8                                 Burrito    7.400000
9                             Canned Soda    1.320577
10                      Canned Soft Drink    1.457641
11                          Carnitas Bowl   10.833971
12                       Carnitas Burrito   10.132712
13                  Carnitas Crispy Tacos   11.137143
14                         Carnitas Salad    8.990000
15                    Carnitas Salad Bowl   11.056667
16                    Carnitas Soft Tacos    9.398500
17      

In [4]:
# Question 02(A): 
# Select only item_name and item_price columns
item_price_df = chipo[['item_name', 'item_price']]
print("DataFrame with item_name and item_price columns:")
print(item_price_df)


DataFrame with item_name and item_price columns:
                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]


In [5]:
#Question 02(B)
# Sort by item_name
sorted_chipo = chipo.sort_values('item_name')
print("Data sorted by item_name:")
print(sorted_chipo[['item_name', 'item_price']])


Data sorted by item_name:
              item_name  item_price
3389  6 Pack Soft Drink       12.98
341   6 Pack Soft Drink        6.49
1849  6 Pack Soft Drink        6.49
1860  6 Pack Soft Drink        6.49
2713  6 Pack Soft Drink        6.49
...                 ...         ...
2384  Veggie Soft Tacos        8.75
781   Veggie Soft Tacos        8.75
2851  Veggie Soft Tacos        8.49
1699  Veggie Soft Tacos       11.25
1395  Veggie Soft Tacos        8.49

[4622 rows x 2 columns]


In [6]:
# Question 03
# Find the row with the most expensive item
most_expensive_item = chipo.sort_values('item_price', ascending=False).iloc[0]
quantity_most_expensive = most_expensive_item['quantity']
print("Quantity of the most expensive item ordered:", quantity_most_expensive)


Quantity of the most expensive item ordered: 15


In [7]:
# Question 04
# Filter for Canned Soda with quantity > 1
canned_soda_more_than_one = chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)]
times_ordered_more_than_one = canned_soda_more_than_one.shape[0]
print("Number of times someone ordered more than one Canned Soda:", times_ordered_more_than_one)


Number of times someone ordered more than one Canned Soda: 20


# Lecture 9.2

### Agenda:

- Questions
- Show us your movies
- Intro to LSU HPC

### Questions

# Lab 9.2

**E.0** Complete the previous labs if you are behind.

**E.1** Submit a screenshot of you using a jupyter notebook on the LSU HPC

**E.2** Complete your final project proposal and submit it in Moodle

**E.3** Prepare a 5 min presentation of your project proposal, including a brief introduction, your research plan, the programming methods you are planning to use, your preliminary results/plots, and your timeline for completion. ​You will present this in class next Tuesday. No late talks this time.

A good target length is 1 slide per minute.

Upload your talk here:
https://lsu.box.com/s/5c95w1s2rrwqy839o3ul3oouzi43s4y1


**Notes** Make notes for yourself on progamming tecniques and commands you learned in the this week, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.