Name:  Sarah Brannum

Lab partner: Miriam Valladares

## Instructions

Tuesday labs are due Friday by midnight.

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner(s)to work with. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your completed score for the chapter assigned in datacamp to the assignment tab in Moodle.

# Lecture 2.1

Lecture Agenda:
* Review of indexing (before warmups)
* Weekly assessment exercise
* questions

A helpful reminder of indexing in python:

![](monty_python_index.jpg)

In [73]:
title = "Monty Python"

In [74]:
# How do I print out "Monty" and "Python"?

print(title[0:5])

print(title[6:12]) # need one more number in index than I want to print

Monty
Python


In [75]:
# You don't have to specify the beginning or the end index

print(title[:5]) #start at zero

print(title[6:]) # end at the end

Monty
Python


In [76]:
# How do I print them out using negative indices?

print(title[-6:]) #have to leave it off since it doesn't need to include the last number in the range

print(title[-12:-7])

print(title[:-7])

Python
Monty
Monty


# Warmups 2.1

**W.1** Create a list of integers from 1-10. Name the list list1. Print the list

In [77]:
list1=list(range(1,11))

**W.2** Print the first element of list1. Then print the last element of list1 on the next line.

In [78]:
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [79]:
print(list1[0])

1


In [80]:
print(list1[-1])

10


**W.3** Print the second element through the ninth element of list1

In [81]:
print(list1[1:9])

[2, 3, 4, 5, 6, 7, 8, 9]


**W.4** Print the sum of the first and last elements of list1

In [82]:
print(list1[0]+list1[-1])

11


**W.5** Print the product of the second and third element of list1

In [83]:
print(list1[1]*list1[2])

6


**W.6** Create a new list of only the even numbers of list1 (using indexing to pull numbers from list1). Name the new list list2. Print list2

In [84]:
list2=[list1[1],list1[3],list1[5],list1[7],list1[9]]
print(list2)

[2, 4, 6, 8, 10]


**W.7** Print the sum of the fifth element of list1 and the fifth element of list2.

In [85]:
print(list1[4]+list1[4])

10


**W.8** Print the product of the second element of list1 and the second element of list2.

In [86]:
print(list1[1]*list2[1])

8


**W.9** Replace the first element of list1 with the integer 5. Print the list

In [87]:
list1[0]=5
print(list1)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.10** Replace the last element of list2 with the integer 5. Print the list

In [88]:
list2[-1]=5
print(list2)

[2, 4, 6, 8, 5]


**W.11** Create a new list that contains list1 and list2. Name the list list3. Print the list.

In [89]:
list3=list1+list2
print(list3)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5]


**W.12** Create a list named list4 which contains list3 + a list of strings containing your full name.

In [90]:
list4=list3+["sarah","margaret","brannum"]
print(list4)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5, 'sarah', 'margaret', 'brannum']


**W.13** Using the commands who and whos, print out lists of all of the variables you just created

In [91]:
who

array1	 array2	 list1	 list2	 list3	 list4	 list4_updated	 math	 max_function	 
max_method	 names	 numpy	 pi	 title	 


In [92]:
whos

Variable        Type        Data/Info
-------------------------------------
array1          ndarray     10: 10 elems, type `int32`, 40 bytes
array2          ndarray     5: 5 elems, type `int32`, 20 bytes
list1           list        n=10
list2           list        n=5
list3           list        n=15
list4           list        n=18
list4_updated   NoneType    None
math            module      <module 'math' (built-in)>
max_function    int         10
max_method      int         10
names           list        n=3
numpy           module      <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
pi              float       3.141592653589793
title           str         Monty Python


**W.14** Now restart your notebook kernel and try printing out the list of variables again. What happened? Explain. 

When you restart the kernal, any variables saved in the jupyter notebook are erased. You have the rerun the cells in order to reinstate the variables into your jupyter notebook.

**W.15** Rerun the cells above to get your variables back, you will need them in the lab below

# Lab 2.1

### Use a combination of markdown text and coding in cells below to answer the below questions.

**E.1** Complete Ch 3 of Introduction to Python in datacamp: Functions and Packages

**E.2** Explain what a function is and how you use one. Give an example.

a function is a a series of codes that can you run together to get an output in python. It is used as a shorter way to run a series of codes together that are done frequently. An example of a function is sum(), which find the sum of multiple elements within the parentheses.

**E.3** How do you get help with a function? Give an example. Explain what the help file is saying

You can type help() into the command line with the function name in the parentheses. An example would be help(sum) which returns the written words on top of the function sum(), often information that is helpful to running the function and what variables are inputs and outputs. When writing a function, whatever you write in the top of the function is what is displayed when you type help().

**E.4** What is a method? How is it different from a function? Demonstrate

A method is similar to a function but belongs to a specific type of object. It is different because it can only be applied to specific data types. It is also called differently, where a function is used like function(x), while a method is used as x.method(). 

In [93]:
#example using function

**E.5** Find the maximum value of one of the lists you created in the warmup exercise two ways, using both a function and a method.

In [94]:
dir(list1) #use function to list out different attributes that are relevant to the specific data type (list in our case)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [95]:
max_function=max(list1)
print(max_function)
list1.sort()
max_method=list1[-1]
print(max_method)

10
10


**E.6** Repeat W.12 using a method

In [96]:
#names=["sarah","margaret","brannum"] --> can't upload in a list together or it adds the list to the list instead of the elements of the list
list3.append("sarah")
list3.append("margaret")
list3.append("brannum")
print(list3)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5, 'sarah', 'margaret', 'brannum']


**E.7** What is a python package?

A python package is a group of functions and methods that can imported and used. You have to import them, but then you can use functions and methods within the package

**E.8** What do you need to do to be able to use an installed package in your code? Give an example here.

In [97]:
#You need to import the package and include either all functions and methods in the package or just the ones you need. Then you can use 
#the functions by calling them from the package
import math #just the package
from math import pi #specific function in the package


**E.9** Import numpy and define an array version of list1 in W.1:   array1.

In [98]:
import numpy
array1=numpy.array(list1)
print(array1)

[ 2  3  4  5  5  6  7  8  9 10]


**E.10** Repeat W.2-W.6 using arrays

In [99]:
#W.2 Print the first element of list1. Then print the last element of list1 on the next line.
#W.3 Print the second element through the ninth element of list1
#W.4 Print the sum of the first and last elements of list1
#W.5 Print the product of the second and third element of list1
#W.6 Create a new list of only the even numbers of list1 (using indexing to pull numbers from list1). Name the new list list2. Print list2

print(list1)
print('W2')
print(array1[0])
print(array1[-1])

print('w3') 
print(array1[1:9])

print('w4') 
print(array1[0]+array1[-1])

print('w5')
print(array1[1]*array1[2])

print('w6')
array2=array1[1: :2]
print(array2)

[2, 3, 4, 5, 5, 6, 7, 8, 9, 10]
W2
2
10
w3
[3 4 5 5 6 7 8 9]
w4
12
w5
12
w6
[ 3  5  6  8 10]


# Scratch