Name Sarah Brannum

Labpartner(s)

In [22]:
# import statements go here
import numpy as np
import matplotlib as plt

# Class 5.1

# Warmups 5.1

**W.1** Go through 1.4.1.2 Creating Arrays in the scipy lecture notes, including the exercises. http://scipy-lectures.org/intro/numpy/array_object.html#id2

In [11]:
a = np.array([0, 1, 2, 3]) #1D
b = np.array([[0, 1, 2], [3, 4, 5]]) #2D
c = np.array([[[1], [2]], [[3], [4]]]) #3D

practice= np.array([[9,7,5,3,1],[8,6,4,2,0]])

print(len(practice)) #gives you the number of rows in numpy array
print(np.shape(practice)) #tells you both rows and columns in numpy array
print(np.ndim(practice)) #gives you just the rows of the numpy array

2
(2, 5)
2


In [9]:
dir(practice)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [14]:
#practice with creating arrays with different attributes
d=np.arange(1,15,2)
print(d)
e=np.linspace(1,15,8)
print(e)
f=np.ones((5,4)) #rows, columns
print(f)
g=np.zeros((5,4))
print(g)
h=np.eye(5,4)
print(h)
i=np.diag([4,7,3,6])
print(i)


[ 1  3  5  7  9 11 13]
[ 1.  3.  5.  7.  9. 11. 13. 15.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[4 0 0 0]
 [0 7 0 0]
 [0 0 3 0]
 [0 0 0 6]]


rand creates matrix of random numbers from 0-1, while randn creates random matrix of a gaussian curve that includes negative numbers too


In [19]:
#random numbers
np.random.seed(1000) #this line will produce the same random integers when run many times, allowing for reproducibility in random runs
j=np.random.rand(5,4) #rows by columns
print(j)

k=np.random.randn(5,4)
print(k)

[[0.65358959 0.11500694 0.95028286 0.4821914 ]
 [0.87247454 0.21233268 0.04070962 0.39719446]
 [0.2331322  0.84174072 0.20708234 0.74246953]
 [0.39215413 0.18225652 0.74353941 0.06958208]
 [0.8853372  0.9526444  0.93114343 0.41543095]]
[[ 1.27179528 -0.98674733 -0.33483545 -0.0994817 ]
 [ 0.4071921   0.91938754  0.31211801  1.53316107]
 [-0.55017387 -0.38314741 -0.82294096  1.60008337]
 [-0.0692813   0.08320949 -0.32692468 -0.04579719]
 [-0.30446006  1.92301013 -0.078659   -0.58206572]]


np.empty gives an array of random values of a specified shape
It would be useful when creating a matrix that will be populated by specific data. It almost acts as a matrix that is empty that you can change the numbers as you go. An example would be to create an np.empty of a specific shape, and then have your code loop through and add a number at a given point for each iteration of the loop.

In [21]:
np.empty([5,4])

array([[1.27179528, 0.98674733, 0.33483545, 0.0994817 ],
       [0.4071921 , 0.91938754, 0.31211801, 1.53316107],
       [0.55017387, 0.38314741, 0.82294096, 1.60008337],
       [0.0692813 , 0.08320949, 0.32692468, 0.04579719],
       [0.30446006, 1.92301013, 0.078659  , 0.58206572]])

# Lecture 5.1

### Agenda:

- Programming questions
- Examples of for loops

# Lab 5.1

**E.1** Complete Lab 4.2 if you haven't allready


**E.2** Complete intermediate python chapter 5: Case study on hacker statistics


**E.3** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [ ]:
# notes: 
# -random walk = combination of random steps

### Congratulations! অভিনন্দন 恭喜 ¡Felicidades! You finished Intermediate Python!