Name Sarah Brannum

Labpartner(s) Miriam

In [1]:
#import statements go here
import pandas as pd
import numpy as np

# Class 9.2

You all will finish presenting your movies from Lab 7.2. 

Today Victoria Garza will give an overview and demo of the LSU HPC system

Reminder your final project proposal is due Monday by 5 PM (note new due date). On Tuesday you will pitch your final project proposal to the class in a short (5 min talk).


# Warmup 9.2

**W.1** Create the following numpy array. Print out the values to check!

[[0. 0. 0. 0. 0. 0. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 5. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 0. 0. 0. 0. 0. 0.]]

In [20]:
array=np.zeros([1,1])
array1=np.pad(array,1, 'constant',constant_values=1)
array2=np.pad(array1,1, 'constant',constant_values=1)
array3=np.pad(array2,1, 'constant',constant_values=0)
array3[3,3]=5
print(array3)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**W.2** Pandas filtering and sorting practice with Chipotle data

Import the dataset from this address https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv
Assign it to a variable called chipo.
1. How many products cost more than $10.00?
2. What is the price of each item?
    1. Print a data frame with only two columns item_name and item_price
    2. Sort by the name of the item
1. What was the quantity of the most expensive item ordered?
1. How many times did someone order more than one Canned Soda?


In [25]:
chipo=pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')
print(chipo.head())

   order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   


In [45]:
chipo['item_price'] = chipo['item_price'].str.replace('$', '').astype(float)
chipo['item_price']
products_over_10 = chipo[chipo['item_price']>10]['item_price'].count()

Total number of products over $10 = 1130 

In [48]:
print(chipo)
print(products_over_10)

      order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description  item_price  
0                                                   NaN        2.39  
1                                          [Clementine]

In [49]:
#What is the price of each item?
#Print a data frame with only two columns item_name and item_price
#Sort by the name of the item

In [54]:
item_name_and_price=chipo[['item_name','item_price']]
item_name_and_price.sort_values('item_name')
print(item_name_and_price)

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]


In [58]:
#What was the quantity of the most expensive item ordered?
most_expensive_price=chipo['item_name'].max()
print(most_expensive_price)
veggie_taco_count = chipo[chipo['item_name']=='Veggie Soft Tacos']['item_name'].count()
print(veggie_taco_count)

Veggie Soft Tacos
7


In [70]:
#How many times did someone order more than one Canned Soda?
practice=chipo.loc[((chipo['item_name']=='Canned Soda') & (chipo['quantity']>=2))]
print(practice)
print(practice.count())
# there are 20 lines to the dataframe that include more than 2 sodas 

      order_id  quantity    item_name choice_description  item_price
18           9         2  Canned Soda           [Sprite]        2.18
51          23         2  Canned Soda     [Mountain Dew]        2.18
162         73         2  Canned Soda        [Diet Coke]        2.18
171         76         2  Canned Soda  [Diet Dr. Pepper]        2.18
350        150         2  Canned Soda        [Diet Coke]        2.18
352        151         2  Canned Soda        [Coca Cola]        2.18
698        287         2  Canned Soda        [Coca Cola]        2.18
700        288         2  Canned Soda        [Coca Cola]        2.18
909        376         2  Canned Soda     [Mountain Dew]        2.18
1091       450         2  Canned Soda       [Dr. Pepper]        2.18
1092       450         2  Canned Soda        [Coca Cola]        2.18
1944       787         2  Canned Soda       [Dr. Pepper]        2.18
2135       859         2  Canned Soda        [Diet Coke]        2.18
2235       901         4  Canned S

# Lecture 9.2

### Agenda:

- Questions
- Show us your movies
- Intro to LSU HPC

### Questions

# Lab 9.2

**E.0** Complete the previous labs if you are behind.

**E.1** Submit a screenshot of you using a jupyter notebook on the LSU HPC

**E.2** Complete your final project proposal and submit it in Moodle

**E.3** Prepare a 5 min presentation of your project proposal, including a brief introduction, your research plan, the programming methods you are planning to use, your preliminary results/plots, and your timeline for completion. ​You will present this in class next Tuesday. No late talks this time.

A good target length is 1 slide per minute.

Upload your talk here:
https://lsu.box.com/s/5c95w1s2rrwqy839o3ul3oouzi43s4y1


**Notes** Make notes for yourself on progamming tecniques and commands you learned in the this week, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

For HPC, can either use SSH or ondemand (LSU GUI to access HPC)
HPC has 3 file systems --> work, home, and project
    - home is where you start, typically only stores scripts and text (smaller space)
    - project doesn't get deleted but isn't backed up either, storage depends on request for allocation
    - work can be deleted but isn't backed up, but also might randomly delete, so not suitable for long term storage
allocation: hpc_smartsc03 (for this class)