Name: 

Lab partner:

## Instructions

Tuesday labs are due Friday by midnight.

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner(s)to work with. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your completed score for the chapter assigned in datacamp to the assignment tab in Moodle.

# Lecture 2.1

Lecture Agenda:
* Review of indexing (before warmups)
* Weekly assessment exercise
* questions

A helpful reminder of indexing in python:

![](monty_python_index.jpg)

In [3]:
title = "Monty Python"

In [4]:
title[0]

'M'

In [5]:
# How do I print out "Monty" and "Python"?

print(title[0:5]) # have to hgave the 5 to get the y

print(title[6:12]) # need one more number in index than I want to print

Monty
Python


In [6]:
# You don't have to specify the beginning or the end index

print(title[:5]) #start at zero

print(title[6:]) # end at the end

Monty
Python


In [7]:
# How do I print them out using negative indices?

print(title[-6:])

print(title[-12:-7])

print(title[:-7])

Python
Monty
Monty


# Warmups 2.1

**W.1** Create a list of integers from 1-10. Name the list list1. Print the list

In [8]:
list1 = [1,2,3,4,5,6,7,8,9,10]
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.2** Print the first element of list1. Then print the last element of list1 on the next line.

In [9]:
print(list1[0])

1


In [10]:
print(list1[-1])

10


**W.3** Print the second element through the ninth element of list1

In [11]:
print(list1[1:-2])

[2, 3, 4, 5, 6, 7, 8]


**W.4** Print the sum of the first and last elements of list1

In [12]:
print(list1[0] + list1[-1])

11


**W.5** Print the product of the second and third element of list1

In [13]:
print(list1[1] * list1[2])

6


**W.6** Create a new list of only the even numbers of list1 (using indexing to pull numbers from list1). Name the new list list2. Print list2

In [14]:
list2 = [list1[1],list1[3], list1[5], list1[-3], list1[-1]]
print(list2)

[2, 4, 6, 8, 10]


**W.7** Print the sum of the fifth element of list1 and the fifth element of list2.

In [15]:
print(list1[4] + list2[-1]) 

15


**W.8** Print the product of the second element of list1 and the second element of list2.

In [16]:
print(list1[1] * list2[1])

8


**W.9** Replace the first element of list1 with the integer 5. Print the list

In [17]:
list1[0] =5
print(list1)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.10** Replace the last element of list2 with the integer 5. Print the list

In [18]:
list2[4] =5
print(list2)


[2, 4, 6, 8, 5]


**W.11** Create a new list that contains list1 and list2. Name the list list3. Print the list.

In [19]:
list3 = list1 + list2
print(list3)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5]


**W.12** Create a list named list4 which contains list3 + a list of strings containing your full name.

In [20]:
list4 = list3 + ["kolin", "tyler", "bilbrew"]
print(list4)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5, 'kolin', 'tyler', 'bilbrew']


**W.13** Using the commands who and whos, print out lists of all of the variables you just created

In [21]:
who

NamespaceMagics	 get_ipython	 json	 list1	 list2	 list3	 list4	 sys	 title	 



**W.14** Now restart your notebook kernel and try printing out the list of variables again. What happened? Explain. 

In [22]:
who

NamespaceMagics	 get_ipython	 json	 list1	 list2	 list3	 list4	 sys	 title	 



In [2]:
whos

Variable          Type             Data/Info
--------------------------------------------
NamespaceMagics   MetaHasTraits    <class 'IPython.core.magi<...>mespace.NamespaceMagics'>
get_ipython       function         <function get_ipython at 0x1048dc9a0>
json              module           <module 'json' from '/opt<...>on3.12/json/__init__.py'>
sys               module           <module 'sys' (built-in)>


**W.15** Rerun the cells above to get your variables back, you will need them in the lab below

# Lab 2.1

### Use a combination of markdown text and coding in cells below to answer the below questions.

**E.1** Complete Ch 3 of Introduction to Python in datacamp: Functions and Packages

**E.2** Explain what a function is and how you use one. Give an example.

In [ ]:
#Functions are a piece of reusable code to solve certain task. You can use a function by  



**E.3** How do you get help with a function? Give an example. Explain what the help file is saying

In [23]:
help(max)
#this will help you figure out how to use the function before using it by typing help()

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



**E.4** What is a method? How is it different from a function? Demonstrate

In [24]:
# a method are functions that belong to objects. It is different from a function because it depends on a certain type.

In [26]:
fam = "bilbrew"
fam.replace("brew","ly")

'billy'

**E.5** Find the maximum value of one of the lists you created in the warmup exercise two ways, using both a function and a method.

In [27]:
max(list1)#function

10

In [32]:
list1= [1,2,3,4,5,6,7,8,9,10]
max(list1)

10

**E.6** Repeat W.12 using a method

In [36]:
list3.append("kolin")

In [38]:
list3.append("bilbrew")

In [39]:
print(list3)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5, 'kolin', 'bilbrew']


**E.7** What is a python package?

In [ ]:
# a python package specifies functions, methods, and types and must be installed

**E.8** What do you need to do to be able to use an installed package in your code? Give an example here.

In [43]:
# in order to use an installed package in your code, you must downlad a pip to install the package. 
# After the install, import the package

import #name of the package you want to use


**E.9** Import numpy and define an array version of list1 in W.1:   array1.

In [41]:
import numpy
array1= numpy.array(list1)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]


**E.10** Repeat W.2-W.6 using arrays

In [46]:
print(array1[0])
print(array1[-1])

1
10


In [49]:
print(array1[1:-2])

[2 3 4 5 6 7 8]


In [50]:
print(array1[0] + array1[-1])

11


In [51]:
array2= numpy.array(array1)
print(array2)

[ 1  2  3  4  5  6  7  8  9 10]


# Scratch