 Name #Kolin Bilbrew

Labpartner(s)

In [6]:
#import statements go here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Class 9.2

You all will finish presenting your movies from Lab 7.2. 

Today Victoria Garza will give an overview and demo of the LSU HPC system

Reminder your final project proposal is due Monday by 5 PM (note new due date). On Tuesday you will pitch your final project proposal to the class in a short (5 min talk).


# Warmup 9.2

**W.1** Create the following numpy array. Print out the values to check!

[[0. 0. 0. 0. 0. 0. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 5. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 0. 0. 0. 0. 0. 0.]]

In [12]:
import numpy as np

# Create the array
array = np.array([
    [0., 0., 0., 0., 0., 0., 0.],
    [0., 1., 1., 1., 1., 1., 0.],
    [0., 1., 1., 1., 1., 1., 0.],
    [0., 1., 1., 5., 1., 1., 0.],
    [0., 1., 1., 1., 1., 1., 0.],
    [0., 1., 1., 1., 1., 1., 0.],
    [0., 0., 0., 0., 0., 0., 0.]
])

print(array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**W.2** Pandas filtering and sorting practice with Chipotle data

Import the dataset from this address https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv
Assign it to a variable called chipo.
1. How many products cost more than $10.00?
2. What is the price of each item?
    1. Print a data frame with only two columns item_name and item_price
    2. Sort by the name of the item
1. What was the quantity of the most expensive item ordered?
1. How many times did someone order more than one Canned Soda?


In [25]:
import numpy as np
import pandas as pd
# Load the dataset
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep='\t')
chipo['item_price'] = chipo['item_price'].replace('[\$,]', '', regex=True).astype(float)

# Filter for products that cost more than $10.00 and count unique items
products_over_10 = chipo[chipo['item_price'] > 10.00]
num_products_over_10 = products_over_10['item_name'].nunique()
num_products_over_10

<>:6: SyntaxWarning: invalid escape sequence '\$'
<>:6: SyntaxWarning: invalid escape sequence '\$'
/var/folders/wq/6qb95y1j1y909jg8q1rds6h80000gn/T/ipykernel_64072/1169770259.py:6: SyntaxWarning: invalid escape sequence '\$'
  chipo['item_price'] = chipo['item_price'].replace('[\$,]', '', regex=True).astype(float)


31

In [19]:
item_prices = chipo.groupby('item_name').agg({'item_price': 'mean'}).reset_index()

# Sort by item_name
item_prices_sorted = item_prices.sort_values('item_name')

# Print the result
print(item_prices_sorted[['item_name', 'item_price']])

                                item_name  item_price
0                       6 Pack Soft Drink    6.610185
1                           Barbacoa Bowl   10.187273
2                        Barbacoa Burrito    9.832418
3                   Barbacoa Crispy Tacos   10.928182
4                     Barbacoa Salad Bowl   10.640000
5                     Barbacoa Soft Tacos   10.018400
6                           Bottled Water    1.867654
7                                    Bowl   14.800000
8                                 Burrito    7.400000
9                             Canned Soda    1.320577
10                      Canned Soft Drink    1.457641
11                          Carnitas Bowl   10.833971
12                       Carnitas Burrito   10.132712
13                  Carnitas Crispy Tacos   11.137143
14                         Carnitas Salad    8.990000
15                    Carnitas Salad Bowl   11.056667
16                    Carnitas Soft Tacos    9.398500
17                          

In [23]:
print(chipo)
print(products_over_10)

      order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description  item_price  
0                                                   NaN        2.39  
1                                          [Clementine]

In [44]:
# Find the most expensive item
most_expensive_item= chipo['item_name'].max()
print(most_expensive_item)

# Find the row with the most expensive item
most_expensive_order = chipo.loc[chipo['item_price'].idxmax()]

# Extract the quantity of the most expensive item
quantity_most_expensive = most_expensive_order['quantity']

print(quantity_most_expensive)

Veggie Soft Tacos
15


In [42]:
canned_soda_orders = chipo.loc[((chipo['item_name'] == 'Canned Soda') & (chipo['quantity']>= 2))]

# Count the number of such orders
count_of_orders = len(canned_soda_orders)
print(canned_soda_orders)
print(count_of_orders)

      order_id  quantity    item_name choice_description  item_price
18           9         2  Canned Soda           [Sprite]        2.18
51          23         2  Canned Soda     [Mountain Dew]        2.18
162         73         2  Canned Soda        [Diet Coke]        2.18
171         76         2  Canned Soda  [Diet Dr. Pepper]        2.18
350        150         2  Canned Soda        [Diet Coke]        2.18
352        151         2  Canned Soda        [Coca Cola]        2.18
698        287         2  Canned Soda        [Coca Cola]        2.18
700        288         2  Canned Soda        [Coca Cola]        2.18
909        376         2  Canned Soda     [Mountain Dew]        2.18
1091       450         2  Canned Soda       [Dr. Pepper]        2.18
1092       450         2  Canned Soda        [Coca Cola]        2.18
1944       787         2  Canned Soda       [Dr. Pepper]        2.18
2135       859         2  Canned Soda        [Diet Coke]        2.18
2235       901         4  Canned S

# Lecture 9.2

### Agenda:

- Questions
- Show us your movies
- Intro to LSU HPC

### Questions

None

# Lab 9.2

**E.0** Complete the previous labs if you are behind.

**E.1** Submit a screenshot of you using a jupyter notebook on the LSU HPC

**E.2** Complete your final project proposal and submit it in Moodle

**E.3** Prepare a 5 min presentation of your project proposal, including a brief introduction, your research plan, the programming methods you are planning to use, your preliminary results/plots, and your timeline for completion. ​You will present this in class next Tuesday. No late talks this time.

A good target length is 1 slide per minute.

Upload your talk here:
https://lsu.box.com/s/5c95w1s2rrwqy839o3ul3oouzi43s4y1


**Notes** Make notes for yourself on progamming tecniques and commands you learned in the this week, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.