Name: Kesse Asante

Labpartner(s)

In [27]:
# import statements go here
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xarray as xr

# Class 5.1

# Warmups 5.1

**W.1** Go through 1.4.1.2 Creating Arrays in the scipy lecture notes, including the exercises. http://scipy-lectures.org/intro/numpy/array_object.html#id2

### 1D

In [28]:
list = np.array([0, 1, 2, 3])
list

array([0, 1, 2, 3])

In [29]:
list.ndim

1

In [30]:
list.shape

(4,)

In [31]:
len(list)

4

### 2D & 3D

In [32]:
list_2 = np.array([[0, 1, 2], [3, 4, 5]])
list_2

array([[0, 1, 2],
       [3, 4, 5]])

In [33]:
list_2.ndim

2

In [34]:
list_2.shape

(2, 3)

In [35]:
len(list_2)

2

### Exercise
Create a simple two dimensional array. First, redo the examples from above. And then create your own: how about odd numbers counting backwards on the first row, and even numbers on the second?
Use the functions len(), numpy.shape() on these arrays. How do they relate to each other? And to the ndim attribute of the arrays?

In [36]:
a = np.array([[9, 7, 5, 3, 1], [10, 8, 6, 4, 2]])
a

array([[ 9,  7,  5,  3,  1],
       [10,  8,  6,  4,  2]])

In [37]:
len(a)

2

In [38]:
a.shape

(2, 5)

In [39]:
a.ndim

2

'len()' tells the size of the first dimension, whilst 'shape()' returns the number of rows and columns of the array. Also the 'ndim' returns the number of dimensions of the array.

### Evenly spaced arrays

In [40]:
e1 = np.arange(10)
e1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
e2 = np.arange(1, 9, 2) # start, end (exclusive), step
e2

array([1, 3, 5, 7])

### By number of points

In [42]:
e3 = np.linspace(0, 1, 6) # start, end, num-points
e3

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [43]:
e4 = np.linspace(0, 1, 5, endpoint = False) #end is not included in list 
e4

array([0. , 0.2, 0.4, 0.6, 0.8])

### Common Arrays

In [44]:
e5 = np.ones((3,3)) #must be double brackets
e5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
e6 = np.zeros((2, 2))
e6

array([[0., 0.],
       [0., 0.]])

In [46]:
e7 = np.eye(3)
e7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
e8 = np.diag(np.array([1, 2, 3, 4]))
e8

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### random numbers

In [48]:
e9 = np.random.rand(4)
e9

array([0.27259261, 0.27646426, 0.80187218, 0.95813935])

In [49]:
e10 = np.random.randn(4)
e10

array([-0.33060682,  0.87412791,  2.00254961,  0.01086208])

In [50]:
np.random.seed(1234) 

In [51]:
e11 = np.random.rand(5)
e11

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581])

In [52]:
e12 = np.empty((3, 3))
e12

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

The function np.empty() from the NumPy library creates a new array without initializing its entries to any specific values. The array will contain whatever values happen to be in memory at the time.

# Lecture 5.1

### Agenda:

- Programming questions
- Examples of for loops

# Lab 5.1

**E.1** Complete Lab 4.2 if you haven't allready


**E.2** Complete intermediate python chapter 5: Case study on hacker statistics


**E.3** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

### My cheat sheet

for i in range(1, 4): # outter loop
    for j in range(1, 4): # inner loop
        print(i, j)
        
Note that python always finishes the inner loop before the outter loop. See output.

for i in range(1, 4): # outter loop
    for j in range(1, 5): # inner loop
        for k in range(1, 3): #inner inner loop
            print(i, j, k)


np.random.seed(123)
outcomes = []
for x in range(10) :
    coin = np.random.randint(0, 2)
    if coin == 0 :
        outcomes.append("heads")
    else :
        outcomes.append("tails")
print(tails)

#Initialize random_walk
random_walk = [0]

NB: Complete the loop
for x in range(100) :
    # Set step: last element in random_walk
    step = random_walk[-1]

    # Roll the dice
    dice = np.random.randint(1,7)

    # Determine next step
    if dice <= 2:
        step = step - 1
    elif dice <= 5:
        step = step + 1
    else:
        step = step + np.random.randint(1,7)

    # append next_step to random_walk
    random_walk.append(step)

NB: Print random_walk
print(random_walk)

for x in range(100) :
    step = random_walk[-1]
    dice = np.random.randint(1,7)

    if dice <= 2:
        step = max(0, step - 1)
    elif dice <= 5:
        step = step + 1
    else:
        step = step + np.random.randint(1,7)

    random_walk.append(step)



Plot random_walk
plt.plot(random_walk)

Show the plot
plt.show()

all_walks = []
for i in range(5) :
    random_walk = [0]
    for x in range(100) :
        step = random_walk[-1]
        dice = np.random.randint(1,7)
        if dice <= 2:
            step = max(0, step - 1)
        elif dice <= 5:
            step = step + 1
        else:
            step = step + np.random.randint(1,7)
        random_walk.append(step)
    all_walks.append(random_walk)

 Convert all_walks to NumPy array: np_aw
np_aw = np.array(all_walks)

 Plot np_aw and show
plt.plot(np_aw)
plt.show()

 Clear the figure
plt.clf()

 Transpose np_aw: np_aw_t
np_aw_t = np.transpose(np_aw)

 Plot np_aw_t and show
plt.plot(np_aw_t)
plt.show()

plt.clf()

 Simulate random walk 20 times
all_walks = []
for i in range(20) :
    random_walk = [0]
    for x in range(100) :
        step = random_walk[-1]
        dice = np.random.randint(1,7)
        if dice <= 2:
            step = max(0, step - 1)
        elif dice <= 5:
            step = step + 1
        else:
            step = step + np.random.randint(1,7)

        # Implement clumsiness
        if np.random.rand() <= 0.005 :
            step = 0

        random_walk.append(step)
    all_walks.append(random_walk)

 Create and plot np_aw_t
np_aw_t = np.transpose(np.array(all_walks))
plt.plot(np_aw_t)
plt.show()

 Simulate random walk 500 times
all_walks = []
for i in range(500) :
    random_walk = [0]
    for x in range(100) :
        step = random_walk[-1]
        dice = np.random.randint(1,7)
        if dice <= 2:
            step = max(0, step - 1)
        elif dice <= 5:
            step = step + 1
        else:
            step = step + np.random.randint(1,7)
        if np.random.rand() <= 0.001 :
            step = 0
        random_walk.append(step)
    all_walks.append(random_walk)

 Create and plot np_aw_t
np_aw_t = np.transpose(np.array(all_walks))

 Select last row from np_aw_t: ends
ends = np_aw_t[-1, : ]

 Plot histogram of ends, display plot
plt.hist(ends)
plt.show()


Count steps greater t
count_steps = np.sum((ends >= 60)/500)
count_steps

### Congratulations! অভিনন্দন 恭喜 ¡Felicidades! You finished Intermediate Python!