Name: Zachary Laird 

Lab partner: Zhenwei Wu

## Instructions

Tuesday labs are due Friday by midnight.

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner(s)to work with. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your completed score for the chapter assigned in datacamp to the assignment tab in Moodle.

# Lecture 2.1

Lecture Agenda:
* Review of indexing (before warmups)
* Weekly assessment exercise
* questions

A helpful reminder of indexing in python:

![](monty_python_index.jpg)

In [9]:
title = "Monty Python"

In [10]:
title[0]

'M'

In [11]:
# How do I print out "Monty" and "Python"?

print(title[0:5])

print(title[6:12]) # need one more number in index than I want to print

Monty
Python


In [12]:
# You don't have to specify the beginning or the end index

print(title[:5]) #start at zero

print(title[6:]) # end at the end

Monty
Python


In [13]:
# How do I print them out using negative indices?

print(title[-6:])

print(title[-12:-7])

print(title[:-7])

Python
Monty
Monty


# Warmups 2.1

**W.1** Create a list of integers from 1-10. Name the list list1. Print the list

In [16]:
list1 = [1,2,3,4,5,6,7,8,9,10]
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [17]:
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

**W.2** Print the first element of list1. Then print the last element of list1 on the next line.

In [19]:
print(list1[0])
print(list1[-1])

1
10


**W.3** Print the second element through the ninth element of list1

In [21]:
list1[1:9]

[2, 3, 4, 5, 6, 7, 8, 9]

**W.4** Print the sum of the first and last elements of list1

In [23]:
list1[0]+list1[-1]

11

**W.5** Print the product of the second and third element of list1

In [25]:
list1[1]*list1[2]

6

**W.6** Create a new list of only the even numbers of list1 (using indexing to pull numbers from list1). Name the new list list2. Print list2

In [27]:
list2 = list1[1], list1[3], list1[5], list1[7], list1[9]
list2

(2, 4, 6, 8, 10)

In [28]:
list2 = [list1[1], list1[3], list1[5], list1[7], list1[9]]
list2

[2, 4, 6, 8, 10]

**W.7** Print the sum of the fifth element of list1 and the fifth element of list2.

In [30]:
list1[4]+list2[4]

15

**W.8** Print the product of the second element of list1 and the second element of list2.

In [32]:
list1[1]*list2[1]

8

**W.9** Replace the first element of list1 with the integer 5. Print the list

In [34]:
list1[0]=5
list1

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10]

**W.10** Replace the last element of list2 with the integer 5. Print the list

In [36]:
list1

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [37]:
list2

[2, 4, 6, 8, 10]

In [38]:
list2[-1]

10

In [39]:
list2[-1] = 5
list2

[2, 4, 6, 8, 5]

**W.11** Create a new list that contains list1 and list2. Name the list list3. Print the list.

In [41]:
list3 = list1 + list2
list3

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5]

**W.12** Create a list named list4 which contains list3 + a list of strings containing your full name.

In [43]:
list4 = [list3, "Zachary", "Gouge", "Laird"]

**W.13** Using the commands who and whos, print out lists of all of the variables you just created

In [45]:
print(list1)
print(list2)
print(list3)
print(list4)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[2, 4, 6, 8, 5]
[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5]
[[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5], 'Zachary', 'Gouge', 'Laird']


**W.14** Now restart your notebook kernel and try printing out the list of variables again. What happened? Explain. 

In [47]:
#The variables are now undefined since we restarted the kernel

**W.15** Rerun the cells above to get your variables back, you will need them in the lab below

# Lab 2.1

### Use a combination of markdown text and coding in cells below to answer the below questions.

**E.1** Complete Ch 3 of Introduction to Python in datacamp: Functions and Packages

**E.2** Explain what a function is and how you use one. Give an example.

A function is a tool you can reuse to accomplish a desired outcome in your code. You would use it to return the value of something. For instance I may use the max() function to return the maximum value in a list

In [54]:
max(list2)

8

**E.3** How do you get help with a function? Give an example. Explain what the help file is saying

To get help with a function you would type out help() and within the parentheses you would
type out the function you need help with

In [57]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(

The help file is first defining what the string function is, while also providing a list of methods using the string function. It also explains errors that may pop up and what the cause of these errors are.

**E.4** What is a method? How is it different from a function? Demonstrate

A method is a prebuilt function that belongs to an object. The difference between methods and functions are that methods are built upon the base of functions. While functions are written by the user to accomplish something, methods have been previously written to accomplish something and all the user must do is attach it to an object. 

In [61]:
# Function
print(type(list1))
#Method
list1.count(2)

<class 'list'>


1

**E.5** Find the maximum value of one of the lists you created in the warmup exercise two ways, using both a function and a method.

In [63]:
#function
max(list1)

10

In [64]:
#using the sort() method, it will sort my list from least to greatest making the last number the maximum value
list1.sort()
print(list1)
#printing the sorted list will give the maximum value as the last number in the list

[2, 3, 4, 5, 5, 6, 7, 8, 9, 10]


**E.6** Repeat W.12 using a method

In [95]:
#Create a list named list4 which contains list3 + a list of strings containing your full name this time using
#a Method|
list3.append("Zachary")
list3.append("Gouge")
list3.append("Laird")
# instead of adding together a list using my first name I can just append list3 and assign it to list4
#now when list4 is printed it should show the appended version of list3
list4 = list3
print(list4)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5, 'Zachary', 'Gouge', 'Laird']


**E.7** What is a python package?

A python package is essentially the directory for python functions, modules, methods, and types. A package stores numerous functions and methods within it and can be directly downloaded into your code. 

**E.8** What do you need to do to be able to use an installed package in your code? Give an example here.

To be able to use an installed package you must import the package into your code. Then using that package name, you must use the package name followed by the method or function from the package you are wanting to use in your code.

In [107]:
import pandas as panda
#This imported the package pandas into python and assigned it to the name panda

**E.9** Import numpy and define an array version of list1 in W.1:   array1.

In [109]:
import numpy

In [111]:
#Using the array function I can create an array version of list1
numpy.array([1,2,3,4,5,6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**E.10** Repeat W.2-W.6 using arrays

In [121]:
# we must now assign a variable to our array to begin executing this step
array1 = numpy.array([1,2,3,4,5,6,7,8,9,10])
#now we are going to print out the first and last elements of array1
print(array1[0])
print(array1[-1])

1
10


In [123]:
#Print the second element through the ninth element of array1
print(array1[1:9])

[2 3 4 5 6 7 8 9]


In [125]:
#Print the sum of the first and last elements of array1
print(array1[0]+array1[-1])

11


In [127]:
#Print the product of the second and third element of array1
print(array1[1]*array1[2])

6


In [131]:
#Create a new list of only the even numbers of array1 (using indexing to pull numbers from list1). 
#Name the new list array2. Print array2
array2 = numpy.array([array1[1], array1[3], array1[5], array1[7], array1[9]])
print(array2)

[ 2  4  6  8 10]


# Scratch