Name: Zachary Laird

Labpartner(s): Sharmin Siddika, Fahmida Akhter, Israt Tama

In [2]:
#import statements go here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lab 4.1

## Instructions

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. Put the name of your lab partner above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your **completed score** for the chapter assigned in datacamp to the assignment tab in Moodle.

# Warmups 4.1

W.1-3 Do exercises 1-3 in the Data Statisics problem: http://scipy-lectures.org/intro/numpy/exercises.html#data-statistics. See lab 4.1  on how to load in the data file

In [6]:
data_np = np.loadtxt('http://scipy-lectures.org/_downloads/populations.txt')
data_np

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

Exercise 1: The mean and std of the populations of each species for the years in the period.

In [7]:
years = data_np[:,0]
hare = data_np[:,1]
lynx = data_np[:,2]
carrots = data_np[:,3]

In [9]:
print("hare",np.mean(hare))
print("lynx",np.mean(lynx))
print("carrots",np.mean(carrots))

hare 34080.95238095238
lynx 20166.666666666668
carrots 42400.0


In [10]:
print("hare", np.std(hare))
print("lynx",np.std(lynx))
print("carrots",np.std(carrots))

hare 20897.906458089667
lynx 16254.591536908763
carrots 3322.5062255844787


Exercise 2: Which year each species had the largest population.


In [17]:
maxhare = np.max(hare)
maxlynx= np.max(lynx)
maxcarrots = np.max(carrots)
print(np.where(hare == maxhare))
print(np.where(lynx == maxlynx))
print(np.where(carrots == maxcarrots))

(array([3], dtype=int64),)
(array([4], dtype=int64),)
(array([0], dtype=int64),)


In [18]:
#Now we find the years
print("hare", years[3])
print("lynx", years[4])
print("carrots", years[0])

hare 1903.0
lynx 1904.0
carrots 1900.0


Exercise 3: Which species has the largest population for each year?

In [19]:
#must create an array without the years 
array = data_np[:,1:]
array

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [29]:
np.argsort?

Signature:       np.argsort(a, axis=-1, kind=None, order=None)
Call signature:  np.argsort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function argsort at 0x000002B68CC64CC0>
File:            c:\users\zlaird1\appdata\local\anaconda3\envs\ocs4001\lib\site-packages\numpy\core\fromnumeric.py
Docstring:      
Returns the indices that would sort an array.

Perform an indirect sort along the given axis using the algorithm specified
by the `kind` keyword. It returns an array of indices of the same shape as
`a` that index data along the given axis in sorted order.

Parameters
----------
a : array_like
    Array to sort.
axis : int or None, optional
    Axis along which to sort.  The default is -1 (the last axis). If None,
    the flattened array is used.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort under the covers and, in general, the

In [30]:
np.argsort(array)

array([[1, 0, 2],
       [1, 0, 2],
       [1, 2, 0],
       [1, 2, 0],
       [0, 2, 1],
       [0, 2, 1],
       [0, 1, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 2, 0],
       [1, 2, 0],
       [2, 1, 0],
       [0, 2, 1],
       [0, 1, 2],
       [0, 1, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2]], dtype=int64)

In [31]:
max_each = np.argmax(array, axis = 1)

In [32]:
type = np.array(['Hare', 'Lynx', 'Carrot'])
maxtype = type[max_each]
maxyears = np.column_stack((years,maxtype))
maxyears
                        

array([['1900.0', 'Carrot'],
       ['1901.0', 'Carrot'],
       ['1902.0', 'Hare'],
       ['1903.0', 'Hare'],
       ['1904.0', 'Lynx'],
       ['1905.0', 'Lynx'],
       ['1906.0', 'Carrot'],
       ['1907.0', 'Carrot'],
       ['1908.0', 'Carrot'],
       ['1909.0', 'Carrot'],
       ['1910.0', 'Carrot'],
       ['1911.0', 'Carrot'],
       ['1912.0', 'Hare'],
       ['1913.0', 'Hare'],
       ['1914.0', 'Hare'],
       ['1915.0', 'Lynx'],
       ['1916.0', 'Carrot'],
       ['1917.0', 'Carrot'],
       ['1918.0', 'Carrot'],
       ['1919.0', 'Carrot'],
       ['1920.0', 'Carrot']], dtype='<U32')

# Lecture 4.1

Agenda:

- Checking in after the hurricane, how is everyone doing?
- Coding questions
- Tabs in python

Some relevant coding humor: https://www.youtube.com/watch?v=JfEIkkDkrmE

Let's go over some of the examples here: https://scipy-lectures.org/intro/language/control_flow.html

In [33]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [35]:
if x[0] == 1:
    print('yes!')

yes!


In [34]:
# if statement

if (x[1] == 3):
    print('yes') # there is a tab before the print statement
    
print('Hello')    # this is not part of the if statement


Hello


In [37]:
if(x[1] == 5):
    print('yes')
elif x[1] == 23 :
    print('yasss')
else :
    print('end of program')

end of program


In [ ]:
y = np.array([4,7,6])
y

In [ ]:
if (y[-1] > 7):
    print("Excellent")

print('Bogus')

# Lab 4.1

**E.1** Complete intermediate python chapter 3: Logic, Control Flow and Filtering

Note that the tutorials here have similar material for your needs:
https://github.com/chsharrison/Sci_comp_F24/blob/main/Course_materials/resources.md

**E.2** Make notes for yourself on all of the progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [40]:
#Can check if the same variable types have relation but not different types
#can use the "and" operator to determine if two booleans are true
#The "or" operator only tests if one of the booleans is True
#Not operator tests the inverse of the boolean
#For arrays you have to use "logical_and()" etc.
#can use x %2 == 0, to check if values are even
#to filter Pandas Dataframe data step 1 is to get the column using x[subset] or loc and iloc
#step 2 is to run the comparison using x[subset] < or > etc. to some value, and store this into a variable
#step 3 is to subset the data frame using x[variable from step 2]
#to do it in one line you would just do x[x[subset] > a value]
#can do the same thing as written above but for boolean operators

**E.3** Exercise 1 on https://www.practicepython.org

In [46]:
name = input("give me your name")
age = input("give me your age")
age = int(age)
Year = 2024 - age + 100
print("The year you turn 100 will be")
print(Year)

give me your name Zach
give me your age 24


The year you turn 100 will be
2100


In [49]:
copies = input(name + " give me a number of your choosing")
print((name+" you will turn 100 years old in the year "+ str(Year)+"\n")*int(copies))

Zach give me a number of your choosing 4


Zach you will turn 100 years old in the year 2100
Zach you will turn 100 years old in the year 2100
Zach you will turn 100 years old in the year 2100
Zach you will turn 100 years old in the year 2100



**E.4** Exercise 2 on https://www.practicepython.org

In [53]:
Numba = int(input("Enter a number to check: "))
Check = int(input("Give me a number to divide with: "))
if Numba % 4 == 0 :
    print(Numba, " is a multiple of 4")
elif Numba % 2 == 0:
    print(Numba, " is even")
else:
    print(Numba, "is odd")
if Numba % Check == 0  :
    print(Numba, "divides evenly by ", Check)
else :
    print(Numba, "does not divide evenly by ", Check)

Enter a number to check:  4
Give me a number to divide with:  2


4  is a multiple of 4
4 divides evenly by  2


Don't forget to do some practicing of what you have been learning, including material from previous labs

**You did it!**