Name: Zachary Laird

Labpartner(s): Sharmin Siddika, Fahmida Akhter, Israt Tama

In [1]:
# import statements go here
import numpy as np
import matplotlib as plt
import pandas as pd

# Class 5.1

# Warmups 5.1

**W.1** Go through 1.4.1.2 Creating Arrays in the scipy lecture notes, including the exercises. http://scipy-lectures.org/intro/numpy/array_object.html#id2

In [2]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [4]:
print(a.ndim)
print(a.shape)
print(len(a))

1
(4,)
4


In [5]:
b = np.array([[0,1,2], [3,4,5]])
print(b.ndim)
print(b.shape)
print(len(b))
c = np.array([[[1], [2]], [[3], [4]]])
print(c)
print(c.shape)

2
(2, 3)
2
[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [7]:
array = np.array([[9,7,5], [20,18,16]])
array

array([[ 9,  7,  5],
       [20, 18, 16]])

In [8]:
len(array)

2

In [9]:
np.shape(array)

(2, 3)

In [12]:
a = np.arange(10)
print(a)
b = np.arange(1,9,2)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


In [13]:
c = np.linspace(0,1,6)
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [14]:
d = np.linspace(0,1,5,endpoint = False)
d

array([0. , 0.2, 0.4, 0.6, 0.8])

In [15]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [17]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
d = np.diag(np.array([1,2,3,4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [20]:
a = np.random.rand(4)
a

array([0.56856927, 0.44768402, 0.0954144 , 0.22297202])

In [21]:
b = np.random.randn(4)
b

array([ 0.60368816, -0.59103242, -0.87348781,  0.8047256 ])

In [22]:
np.random.seed(1234)

In [25]:
zach = np.arange(2,44+1, 4 )
zach

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42])

In [27]:
boo = np.linspace(10,40,3)
boo

array([10., 25., 40.])

In [30]:
yyz = np.ones((12,4))
yyz

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
zero = np.zeros((4,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
s = np.eye((4))
s

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
q = np.diag(np.array([4,7,8,9]))
q

array([[4, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [47]:
np.random.seed(2)
r = np.diag(np.random.randn(4))
r

array([[-0.41675785,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.05626683,  0.        ,  0.        ],
       [ 0.        ,  0.        , -2.1361961 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.64027081]])

In [61]:
qq = np.array((np.random.rand(2)))
qq

array([0.18443987, 0.78533515])

In [48]:
np.empty?

Docstring:
empty(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, without initializing entries.

Parameters
----------
shape : int or tuple of int
    Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    Desired output data-type for the array, e.g, `numpy.int8`. Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of uninitialized (arbitrary) data of the gi

In [55]:
np.empty((3,2))

array([[7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304]])

In [56]:
#produces an array of the same number recurring x amount of times.
#Useful for when you need an array of the same number to match against another array
#using for x in a range you can create a random "walk"
#knowing the distribution of random walks allows you to calculate chances
#by taking that for range, you can create a histogram displaying the distribution

# Lecture 5.1

### Agenda:

- Programming questions
- Examples of for loops

In [63]:
l1 = ["eat", "sleep", "repeat"]
for x, y in enumerate(l1):
    print("Index " +str(x) + ": " + str(y))

Index 0: eat
Index 1: sleep
Index 2: repeat


In [75]:
for i in range(1,3):
    for j in range(1,5):
        for k in range(1,3):
            print(i,j,k)

1 1 1
1 1 2
1 2 1
1 2 2
1 3 1
1 3 2
1 4 1
1 4 2
2 1 1
2 1 2
2 2 1
2 2 2
2 3 1
2 3 2
2 4 1
2 4 2


# Lab 5.1

**E.1** Complete Lab 4.2 if you haven't allready


**E.2** Complete intermediate python chapter 5: Case study on hacker statistics


**E.3** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [ ]:
# inside numpy is the random function and this generates random numbers
#the .seed function sets the same random numbers (allows for reproducibility)
#randint allows you to choose a range of integers for random selection
#

### Congratulations! অভিনন্দন 恭喜 ¡Felicidades! You finished Intermediate Python!

YAYYYYYYY!!!